---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-gnb1
  labels:
    app: ueransim
    component: gnb1
spec:
  selector:
    matchLabels:
      app: ueransim
      component: gnb1
  replicas: 
  template:
    metadata:
      labels:
        app: ueransim
        component: gnb1
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "n2network", "interface": "n2", "ips": [ "10.12.2.101/24" ] },
          { "name": "n3network", "interface": "n3", "ips": [ "10.12.3.101/24" ] }
          ]'
    spec:
      containers:
      - image: ghcr.io/niloysh/ueransim:v3.2.6
        name: gnb
        ports:
        - name: gnb-ue
          containerPort: 4997
          protocol: UDP
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command: [ "/ueransim/config/wrapper.sh" ]
        volumeMounts:
        - mountPath: /ueransim/config
          name: gnb-volume
        resources:
          requests:
            memory: "1024Mi" # "512Mi"#"4096Mi" # "2048Mi" # "512Mi" # 
            cpu: "750m" # "1000m" # "500m"#"2000m" # "750m" # "1000m" # "500m"
          limits:
            memory: "2048Mi" # "1024Mi"#"4096Mi" # "3072Mi" # "2048Mi" # 
            cpu: "1000m" #"1500m" # "1000m"#"4000m" #"1500m" # "1000m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: gnb-volume
        configMap:
          name: gnb1-configmap
          items:
          - key: gnb-config.yaml
            path: gnb-config.yaml
          - key: wrapper.sh
            path: wrapper.sh
            mode: 0777
