apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganache-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: ganache
  template:
    metadata:
      labels:
        app: ganache
    spec:
      containers:
        - name: ganache
          image: ghcr.io/pzeina/ganache  # Replace with your Ganache Docker image and tag
          ports:
            - containerPort: 8545  # Ganache JSON-RPC port
