apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-ausf
  labels:
    app: free5gc
    nf: ausf
spec:
  selector:
    matchLabels:
      app: free5gc
      nf: ausf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc
        nf: ausf
    spec:
      initContainers:
      - name: wait-nrf
        image: appropriate/curl
        command: ['sh', '-c', 'until curl -s -o /dev/null -w "%{http_code}" http://nrf-nnrf:8000 | grep "200"; do sleep 1; done;']
      containers:
      - image: ghcr.io/pzeina/free5gc-ausf:latest
        name: ausf
        ports:
        - containerPort: 8000
        command: ["./ausf"]
        args: ["--config", "config/ausfcfg.yaml"]  
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /free5gc/config/
          name: ausf-volume
        resources:
          requests:
            memory: "512Mi"
            cpu: "1000m" # "1250m" # "2250m" # "500m"
          limits:
            memory: "1024Mi"
            cpu: "2500m" # "1500m" # "2500m" # "1000m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: ausf-volume
        projected:
          sources:
          - configMap:
              name: ausf-configmap
