---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-gnb2
  labels:
    app: ueransim
    component: gnb2
spec:
  selector:
    matchLabels:
      app: ueransim
      component: gnb2
  replicas: 
  template:
    metadata:
      labels:
        app: ueransim
        component: gnb2
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "5gnetwork", "interface": "n3", "ips": [ "129.97.168.132/24" ] },
          { "name": "5gnetwork", "interface": "n2", "ips": [ "129.97.168.142/24" ] }
          ]'
    spec:
      containers:
      - image: ghcr.io/niloysh/ueransim:v3.2.6
        name: gnb
        ports:
        - name: gnb-ue
          containerPort: 4997
          protocol: UDP
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command: [ "/ueransim/config/wrapper.sh" ]
        volumeMounts:
        - mountPath: /ueransim/config
          name: gnb-volume
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: gnb-volume
        configMap:
          name: gnb2-configmap
          items:
          - key: gnb-config.yaml
            path: gnb-config.yaml
          - key: wrapper.sh
            path: wrapper.sh
            mode: 0777
